# Generated by Django 5.2.4 on 2025-07-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year_of_production', models.CharField(max_length=4)),
                ('dimensions', models.CharField(max_length=100)),
                ('authentication', models.CharField(max_length=100)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('start_time', models.DateTimeField()),
                ('shipping_options', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, help_text='Upload auction item image', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('availability_status', models.CharField(max_length=50)),
                ('image_url', models.ImageField(blank=True, help_text='Upload product image', upload_to='images/')),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(default='Default User', help_text='Name of the bidder (defaults for MVP)', max_length=100)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.auctionitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
